- id: '1602021274426'
  alias: Turn off the lights when Tarald leaves home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.tarald
    zone: zone.home
    event: leave
  condition: []
  action:
  - domain: light
    entity_id: light.master_bedroom
    device_id: ee437d8f07f611eb80bcddfe71bc5533
    type: turn_off
  mode: single
- id: '1602021604754'
  alias: Turn off the lights when Tiril leaves home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.tiril
    zone: zone.home
    event: leave
  - platform: state
    entity_id: device_tracker.tiril
    from: home
    to: not_home
  condition: []
  action:
  - domain: light
    entity_id: light.tirils_light
    device_id: 1d03e04707f711eb8dd9093de4e0c329
    type: turn_off
  mode: single
- id: '1602021640328'
  alias: Turn off the lights when Tuva leaves home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.tuva
    zone: zone.home
    event: leave
  - platform: state
    entity_id: device_tracker.tuva
    from: home
    to: not_home
  condition: []
  action:
  - domain: light
    entity_id: light.tuvas_light
    device_id: 1cfe021907f711eb8596a17005fb56f4
    type: turn_off
  mode: single
- id: '1602051006204'
  alias: Turn off the lights when Trym leaves home
  description: ''
  trigger:
  - platform: state
    entity_id: person.trym
    from: home
    to: not_home
  - platform: state
    entity_id: person.trym
    to: School
  condition: []
  action:
  - domain: light
    entity_id: light.tryms_light
    device_id: 1d0348ec07f711eb86a04b3e391d30b7
    type: turn_off
  mode: single
- id: '1602062514061'
  alias: Welcome Trym
  description: Greet Trym when he comes home
  trigger:
  - platform: state
    entity_id: person.trym
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome home, Princess Trym. You are a very handsome boy.
  mode: single
- id: '1602062742033'
  alias: Welcome Tuva
  description: Greet Tuva when she comes home
  trigger:
  - platform: state
    entity_id: person.tuva
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    entity_id: media_player.livingroom_hub
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome home, Bad-ass Bobby. You are a fantastic girl, and I love you
        very much.
  mode: single
- id: '1602062841779'
  alias: Welcome Tiril
  description: Greet Tiril when she comes home
  trigger:
  - platform: state
    entity_id: person.tiril
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome home, Tirel. You are awesome in every way.
  mode: single
- id: '1602257268347'
  alias: Welcome Jeanette
  description: Greet Jeanette when she comes home
  trigger:
  - platform: state
    from: not_home
    to: home
    entity_id: person.jeanette
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:50
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    entity_id: media_player.livingroom_hub
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome home, Jeanette. This house just isn't complete without you.
  mode: single
- id: '1602270734280'
  alias: Deactivate voice greetings
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.welcome_greetings
  mode: single
- id: '1602270765289'
  alias: Activate voice greetings
  description: ''
  trigger:
  - platform: time
    at: 07:00
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.welcome_greetings
  mode: single
- id: '1602271043499'
  alias: Rise and Shine
  description: Wake us in the morning
  trigger:
  - platform: time
    at: 07:30:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.tradfri_outlet
  - service: tts.google_translate_say
    data:
      entity_id:
      - media_player.nightmare_speaker
      - media_player.hell
      - media_player.bedroom_mini
      - media_player.living_room_speaker
      message: Good morning, time to rise and shine
  mode: single
- id: '1602404607655'
  alias: Welcome Tarald
  description: Greet Tarald when he comes home
  trigger:
  - platform: state
    entity_id: person.tarald
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome home, My Master. I live to serve you!
  mode: single
- id: '1602582667255'
  alias: Notify when Jeanette leaves work
  description: ''
  trigger:
  - platform: zone
    entity_id: person.jeanette
    zone: zone.hth
    event: leave
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Jeanette has left work
  mode: single
- id: '1602776159785'
  alias: Lounge playing
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.lounge
    to: playing
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      device_id: ed2918bbc2e32bb07c97b97478718978
  - service: media_player.select_source
    data:
      source: Lounge
    target:
      device_id: ed2918bbc2e32bb07c97b97478718978
  mode: single
- id: '1602776965519'
  alias: Lounge Status
  description: ''
  trigger:
  - platform: state
    entity_id: remote.das_hub
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.attributes.current_activity == \"Lounge Music\"\n
      \     }}"
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.lounge_on
  mode: single
- id: '1604003259633'
  alias: Welcome Kent
  description: Greet Kent when he visits
  trigger:
  - platform: state
    entity_id: device_tracker.kents_mobil
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome master Kent. I expect there will be fun and games now
  mode: single
- id: '1610014036256'
  alias: TV Surround
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.das_tv
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.pioneer_avr
  - service: media_player.select_source
    data:
      source: TV
    target:
      entity_id: media_player.das_tv
  mode: single
- id: '1610016789987'
  alias: TV Surround Off
  description: When turning off TV
  trigger:
  - platform: state
    entity_id: media_player.das_tv
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.pioneer_avr
  mode: single
- id: '1610405925345'
  alias: Evening
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.tradfri_outlet
  mode: single
- id: '1615133913987'
  alias: Wake Tiril
  description: Wake Tiril in the mornings
  trigger:
  - platform: time
    at: 07:35
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: spotcast.start
    data:
      account: tiril
      device_name: Hell
      uri: spotify:track:53sSF069DeO67sgt9d4BOU
  mode: single
- id: '1615791226951'
  alias: Wake Tuva
  description: Wake Tuva in the mornings
  trigger:
  - platform: time
    at: 07:40
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: spotcast.start
    data:
      account: tuva
      device_name: Nightmare speaker
      uri: spotify:track:53sSF069DeO67sgt9d4BOU
  mode: single
- id: '1620138244953'
  alias: Welcome Nora
  description: Greet Nora when she visits
  trigger:
  - platform: state
    entity_id: device_tracker.blablabopibop_3
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome Mistress Nora. It is always nice to see you
      language: English
  mode: single
- id: '1620138600116'
  alias: Welcome Victor
  description: Greet Victor when he visits
  trigger:
  - platform: state
    entity_id: device_tracker.viktorsiniphone_3
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.welcome_greetings
    state: 'on'
  action:
  - delay: 00:00:30
  - service: tts.google_translate_say
    data:
      entity_id: media_player.livingroom_hub
      message: Welcome Victor. You're a clever boy, and it's a pleasure to have you
        drop by
  mode: single
- id: '1621202110872'
  alias: SHIELD Surround
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.shield_pro
    to: playing
    from: idle
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.pioneer_avr
  - service: media_player.select_source
    data:
      source: Shield
    target:
      entity_id: media_player.pioneer_avr
  - service: media_player.volume_set
    target:
      entity_id: media_player.das_tv
    data:
      volume_level: 0
  mode: single
- id: '1623684335475'
  alias: Out of Disk
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: '90'
  condition: []
  action:
  - service: notify.mobile_app_das_ifon
    data:
      message: Disk almost full!
  mode: single
- id: '1623684736423'
  alias: Lounge off
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.lounge
    to: 'off'
  condition: []
  action:
  - service: media_player.turn_off
    target:
      device_id: ed2918bbc2e32bb07c97b97478718978
  mode: single
- id: '1623762692151'
  alias: Sonos Battery Warning
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sonos_roam_battery
    below: '10'
  condition: []
  action:
  - service: notify.mobile_app_das_ifon
    data:
      message: Sonos Roam almost dead!
  mode: single
- id: '1634061868991'
  alias: Out of Memory
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.memory_use_percent
    above: '95'
  condition: []
  action:
  - service: notify.mobile_app_das_ifon
    data:
      message: Memory almost full!
  mode: single
- id: '1634061897521'
  alias: Out of Swap
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.swap_use_percent
    above: '90'
  condition: []
  action:
  - service: notify.mobile_app_das_ifon
    data:
      message: Swap almost full!
  mode: single
- id: '1639475198489'
  alias: Keep IKEA running
  description: ''
  trigger:
  - platform: state
    entity_id: light.tryms_light
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 419008cc7270d1ebdd3e189126bb976f
  mode: single
- id: '1653515808637'
  alias: Scheduled Internet Downtime
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.ischedule
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.enforce_iaccess_schedule
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.scheduled_iclients
  mode: single
- id: '1653515871699'
  alias: Scheduled Internet Uptime
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.ischedule
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: input_boolean.ischedule
  mode: single
- id: '1661762239257'
  alias: Color Loop - Downstairs
  description: Cycles colours in all lights in the Lounge, Dining room and the Kitchen.
    Use it for party time! :)
  use_blueprint:
    path: hugalafutro/Color_Loop.yaml
    input:
      cl_light:
        entity_id:
        - light.lounge_lights
        - light.dining_room_lights
        - light.kitchen_lights
